

public enum Settings {
	COAP_ACK_RANDOM_FACTOR,
	COAP_ACK_TIMEOUT,
	COAP_MAX_RETRANSMIT,
	COAP_MESSAGETYPE,
	COAP_NSTART,
	META_AUTHOR,
	META_TITLE,
	TEST_INTERMISSION,
	TEST_NTPPORT,
	TEST_PARALLELTRANSFERS,
	TEST_REPEATS,
	TEST_SERVER,
	TEST_SERVERPORT,
	TEST_TESTPORT,
	TRAFFIC_BLOCKSIZE,
	TRAFFIC_BURST_TIME,
	TRAFFIC_FILESIZE,
	TRAFFIC_MAXSENDTIME,
	TRAFFIC_IDLE_TIME,
	TRAFFIC_MAXMESSAGES,
	TRAFFIC_MESSAGESIZE,
	TRAFFIC_MODE,
	TRAFFIC_RATE,
	TRAFFIC_TYPE,
	TRAFFIC_NRTHREADS
}
